
services:
  petcenter-fe:
    container_name: petcenter-fe
    build:
      context: .
      dockerfile: Dockerfile
      target: deps          # chỉ cần cài dep; bỏ qua bước build production
    command: npm run dev    # hot reload
    volumes:
      - .:/app              # mount mã nguồn
      - /app/node_modules   # tránh đè node_modules của container
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    cpus: 1
    mem_limit: 512M
