jwt:
  signerKey: "Wg6f2yDwnlvjU4/EzCme746jY54aE19ovQ+giBlTApLMqvtBqXvMgB8vwG6DCqkA"
  valid-duration: 3600 #in second
  refreshable-duration: 360000 #in second

vnp:
  tmn-code: HUUXL4C6
  hash-secret: 2548W0FS0J3PPLO8RTGIGT57SX1TXRG1
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8080/petcenter/payment/vnpay/return

fe:
  success-url: http://localhost:3000/invoice/vnpay

