server:
  port: 8080
  servlet:
    context-path: /petcenter
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/petcenter"
    username: root
    password: trunganh
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  signerKey: "Wg6f2yDwnlvjU4/EzCme746jY54aE19ovQ+giBlTApLMqvtBqXvMgB8vwG6DCqkA"
  valid-duration: 3600 #in second
  refreshable-duration: 360000 #in second

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.example.BE: DEBUG

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    displayRequestDuration: true
    disable-swagger-default-url: true
  show-actuator: false
  paths-to-match: /**
