services:
  # MySQL Database Service
  mysql-db:
    image: mysql:8.0
    container_name: petcenter-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: trunganh
      MYSQL_DATABASE: petcenter
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - petcenter-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=trunganh"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    # cpus: 0.5
    # mem_limit: 512M
    # deploy:
    #   resources:
    #     limits:
    #       memory: 512M
    #       cpus: '0.5'
    #     reservations:
    #       memory: 256M
    #       cpus: '0.25'

  # Pet Center Application Service
  petcenter-be:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petcenter-be
    restart: unless-stopped
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      # Database configuration - match exactly with application.yaml spring.datasource structure
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/petcenter?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: trunganh
      SPRING_DATASOURCE_DRIVERCLASSNAME: com.mysql.cj.jdbc.Driver
      
      # JPA configuration - match exactly with application.yaml spring.jpa structure
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: false
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      
      # JWT configuration - match exactly with application.yaml jwt structure
      JWT_SIGNERKEY: Wg6f2yDwnlvjU4/EzCme746jY54aE19ovQ+giBlTApLMqvtBqXvMgB8vwG6DCqkA
      JWT_VALID_DURATION: 3600
      JWT_REFRESHABLE_DURATION: 360000
      
      # Logging configuration - match exactly with application.yaml logging.level structure
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: WARN
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: WARN
      LOGGING_LEVEL_COM_EXAMPLE_BE: INFO
    ports:
      - "8080:8080"
    volumes:
      - app_logs:/app/logs
    networks:
      - petcenter-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/petcenter/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # cpus: 3.0
    # mem_limit: 3G
    # deploy:
    #   resources:
    #     limits:
    #       memory: 2G
    #       cpus: '2.0'
    #     reservations:
    #       memory: 512M
    #       cpus: '0.5'

# Named volumes for data persistence
volumes:
  mysql_data:
    driver: local
  app_logs:
    driver: local

# Custom network
networks:
  petcenter-network:
    driver: bridge
